name: Docker container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
         - 27017:27017

      steps:
        - name: Post a user
          run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\": \"Alex\",\"address\":\"lenina\"}'"
        - name: Get all users
          run: curl http://localhost:3001/api/user