name: Docker container
on: push

jobs:
  docker-in-steps:
    runs-on: ubuntu-latest
    container:
      image: node:14-alpine
    steps:
      - name: log node version
        run: node -v
      - name: steps with docker-in-step
        uses: docker://node:16-alpine
        with:
         entrypoint: '/bin/echo'
         args: 'Hello world'
      - name: steps with docker-in-syep2
        uses: docker://node:16-alpine
        with:
         entrypoint: /usr/local/bin/node
         args: -v
      - uses: actions/checkout@v2
      - name: Runs sh script
        uses: docker://node:16-alpine
        with:
         entrypoint: ./script.sh
         args: "Some"
  docker-in-service:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
         - 27017:27017
    steps:
      - name: Post a user
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\": \"Alex\",\"address\":\"lenina\"}'"
      - name: Get all users
        run: curl http://localhost:3001/api/users