# https://docs.github.com/en

name: Shell Commands
# выбираем при каком действии будут запускаться экшн, можно писать on: [push, pull]
on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    # указываем максимольное время выполнения работы перез тем как github отмение ее, по умолчанию 6 часов
    # timeout-minutes: 360
    steps:
      - name: Echo a string
        run: echo "Hello world"
        # запустит все последующие шаги если любой  предыдущий зафейлится
        continue-on-error: true
      - name: multiline script
        run: |
          node -v
          npm -v
        # указываем максимольное время выполнения ifuf перез тем как github отмение его, по умолчанию 0
        # timeout-minutes: 0
      - name: python Commands
        run: |
          import platform
          print
          (platform.processor())
        shell: python
  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory Powershell
        run: Get-Location

      - name: Directory Bash
        run: pwd
        shell: bash
